FROM node:20-alpine AS expo-builder

WORKDIR /app

COPY package*.json ./
RUN npm ci || npm install --legacy-peer-deps

COPY . .

# Compila o build estático do Expo Web (gera a pasta /app/dist)
RUN npx expo export -p web

FROM nginx:1.27-alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=expo-builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
